version: '3.2'
services:
  mysql:
    image: mysql:5.7
    # https://stackoverflow.com/questions/46004648/how-to-setup-mysql-with-utf-8-using-docker-compose/46004865
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    ports:
      - 9876:3306
    environment:
      MYSQL_DATABASE: 'studybuddies_test'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    volumes:
      - ./scripts/init-test-db.sql:/docker-entrypoint-initdb.d/init.sql
