name: Test CI

on:
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MYSQL_DATABASE: studybuddies_test

      services:
        mysql:
          image: mysql:5.7
          env:
            MYSQL_ROOT_PASSWORD: 1234
          ports:
            - 9876:3306

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn test
