name: Test CI

on:
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MYSQL_DATABASE: studybuddies_test
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 1234
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 9876

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 9876:9876

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn test
